name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # Trigger the pipeline on pushes to the develop branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Raspberry Pi
      run: |
        ssh pi@192.168.178.73 'cd ~/LED && ./deploy_script.sh'
